[assembly: System.Reflection.AssemblyVersion("1.3.0")] // Generated by build
[assembly: System.Reflection.AssemblyFileVersion("1.3.0")] // Generated by build
[assembly: System.Reflection.AssemblyInformationalVersion("1.3.0-rc1")] // Generated by build
