AllowedHosts: "*"
Kestrel:
  Endpoints:
    Https:
      Url: https://localhost:9998
    Http:
      Url: http://localhost:9999
# For more details check the following:
# https://nblumhardt.com/2021/06/customize-serilog-text-output/
Serilog:
  Using: Serilog.Sinks.Console, Serilog.Expressions, Serilog.Sinks.Graylog
  MinimumLevel:
    Default: Debug
    Override:
      System: Warning
      Microsoft: Warning
      Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware: Information
      Microsoft.Hosting.Lifetime: Information
      Serilog.AspNetCore.RequestLoggingMiddleware: Information
  WriteTo:
    - Name: Console
      Args:
        formatter:
          type: Serilog.Templates.ExpressionTemplate, Serilog.Expressions
          template: "{@t:HH:mm:ss} | {@l:u3} | {SourceContext, -50} | {#if @p['TraceID'] is not null}{@p['TraceID']} {@p['Request']} | {#end}{@m}\n{@x}"
          theme: Serilog.Templates.Themes.TemplateTheme::Code, Serilog.Expressions
    - Name: Graylog
      Args:
        hostnameOrAddress: graylog.gbworks.lan
        port: 12201
        transportType: Udp
        facility: SimpleAPI
