SchedulerSettings:
    Jobs:
        -   Name: Test1
            Active: true
            CronExpression: '0/10 * * * * ?'
            JobType: QuartzHostedService.Samples.SecondJob
        -   Name: Test2
            CronExpression: '0/8 * * * * ?'
            JobType: QuartzHostedService.Samples.SampleJob
            Parameters:
            -   State: Second Job
            -   Id: My ID
            -   Name: CommandName
            -   Dot: 32
        -   Name: Test3
            Active: false
            CronExpression: '0/32 * * * * ?'
            JobType: QuartzHostedService.Samples.SampleJob